namespace GraveyardKeeper2Accessibility;

/// <summary>
/// Plugin identity. Hardcoded rather than generated by BepInEx.PluginInfoProps so the build has
/// no NuGet dependency at all - every reference this project needs is a file on disk.
/// Version is the one exception: the build writes it into PluginVersion.g.cs from the newest
/// "## X.Y.Z" entry in CHANGELOG.md, so the changelog, the zips and the plugin can never disagree.
/// </summary>
internal static partial class PluginInfo
{
    internal const string Guid = "svenja001.gk2.accessibility";
    internal const string Name = "Graveyard Keeper II Accessibility";
}
